CREATE TABLE Role (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE client (
  id SERIAL PRIMARY KEY,
  fcs VARCHAR(255),
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  inn INTEGER,
  phone VARCHAR(255),
  date_of_birth TIMESTAMP,
  work_place VARCHAR(255),
  address VARCHAR(255),
  status BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  role_id INTEGER NOT NULL DEFAULT 1,
  FOREIGN KEY (role_id) REFERENCES role(id)
);

CREATE TABLE passport (
  id SERIAL PRIMARY KEY,
  serial_and_number INTEGER UNIQUE NOT NULL,
  birth_place VARCHAR(255),
  date_of_issue TIMESTAMP NOT NULL,
  issuing_authority VARCHAR(255),
  client_id INTEGER,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (client_id) REFERENCES client(id)
);



CREATE TABLE post (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  salary FLOAT NOT NULL,
  description VARCHAR(255),
  requirements VARCHAR(255),
  duties VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE employee (
  id SERIAL PRIMARY KEY,
  fc VARCHAR(255) NOT NULL,
  inn INTEGER NOT NULL,
  phone VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  date_of_birth TIMESTAMP NOT NULL,
  address VARCHAR(255) NOT NULL,
  post_id INTEGER NOT NULL,
  passport_id INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (post_id) REFERENCES post(id),
  FOREIGN KEY (passport_id) REFERENCES passport(id)
);

CREATE TABLE account (
  id SERIAL PRIMARY KEY,
  status BOOLEAN NOT NULL DEFAULT TRUE,
  close_date TIMESTAMP,
  client_id INTEGER UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (client_id) REFERENCES client(id)
);

CREATE TABLE card (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  card_number VARCHAR(255) NOT NULL,
  expiration_date VARCHAR(255),
  cvv INTEGER NOT NULL,
  account_id INTEGER NOT NULL,
  balance INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (account_id) REFERENCES account(id)
);

CREATE TABLE credit (
  id SERIAL PRIMARY KEY,
  type VARCHAR(255) NOT NULL,
  rate FLOAT NOT NULL,
  term VARCHAR(255) NOT NULL,
  conditions VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE loan (
  id SERIAL PRIMARY KEY,
  account_id INTEGER NOT NULL,
  credit_id INTEGER NOT NULL,
  time TIMESTAMP NOT NULL,
  initial_sum FLOAT NOT NULL,
  due_for_repayment FLOAT NOT NULL,
  term VARCHAR(255) NOT NULL,
  monthly_payment FLOAT NOT NULL,
  overpayment FLOAT NOT NULL,
  aim VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (account_id) REFERENCES account(id),
  FOREIGN KEY (credit_id) REFERENCES credit(id)
);

CREATE TABLE exchange (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  purchase_rate FLOAT NOT NULL,
  sale_rate FLOAT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE loan_payment (
  id SERIAL PRIMARY KEY,
  payment_amount FLOAT NOT NULL,
  card_id INTEGER,
  loan_id INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (card_id) REFERENCES card(id),
  FOREIGN KEY (loan_id) REFERENCES loan(id)
);

CREATE TABLE atm (
  id SERIAL PRIMARY KEY,
  location VARCHAR(255) NOT NULL,
  open_date TIMESTAMP NOT NULL,
  balance FLOAT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE transaction (
  id SERIAL PRIMARY KEY,
  sum FLOAT NOT NULL,
  status VARCHAR(255) NOT NULL,
  sender_card_id INTEGER NOT NULL,
  getter_card_id INTEGER NOT NULL,
  fee FLOAT,
  description VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (sender_card_id) REFERENCES card(id),
  FOREIGN KEY (getter_card_id) REFERENCES card(id)
);
